### ISSUE TITLE
Dynamic demeaning

### ISSUE THREAD

**Issue by jamescmorley** [crstnn/BeveridgeNelsonFilter#11]
For the demeaning option dropdown, I think maybe we should have the title be "Demeaning" instead of "Iterative Dynamic Demeaning".

Then for the options, I'd go with "Constant" instead of "Static Demean" and "Iterative Dynamic Demeaning".

It does beg a question of whether we want to reintroduce the regular (1 step) "Dynamic Demeaning" as an option too, as this is what was considered in the original KMW paper. So there would be three options:

Constant
Dynamic Demeaning
Iterative Dynamic Demeaning

and the "Rolling Window" option would just be accessible when either of the latter two options is taken (note: I'd say "Rolling Window" instead of "Manual Rolling Window". 

Also, I think the "Iterative Backcasting" option should be on the previous page under "Data Transformations and Adjustments".

I'm coming back around to keeping the Differencing Method and Computed Percentages options as is. However, I'd make "Multiply by 100" as the default (along with "No Differencing (Levels)".

<img width="287" alt="Screen Shot 2022-03-29 at 4 04 18 pm" src="https://user-images.githubusercontent.com/85649168/160537194-50fc334a-2035-447c-9d10-81b19ff1876a.png">

**Comment by crstnn** [comment]
So what option does the "Iterative Dynamic Demeaning" correspond to now?
Is it an amalgam of Iterative Backcasting and and Dynamic Demeaning?

**Comment by jamescmorley** [comment]
Iterative dynamic demeaning is when in the R code "iterative <- 100" or some other number >1 (what is it set to?). Regular "dynamic demeaning" is when "iterative <- 1". Static demeaning (aka "constant") is when "iterative <- 0".

**Comment by jamescmorley** [comment]
Iterative backcasting is a separate issue from dynamic demeaning.
