### ISSUE TITLE
Iterative backcasting always on (not an option)

### ISSUE THREAD

**Issue by jamescmorley** [crstnn/BeveridgeNelsonFilter#15]
Can we remove the tickbox for iterative backcasting from the website and always have iterative backcasting as the background option?

**Comment by crstnn** [comment]
Wouldn't it be better to leave it as default and give people the option to change it like they could in the code. Unless it's integral to the paper?

**Comment by jamescmorley** [comment]
Ben and I thought this might be a case of simpler is better. There would be little reason *not* to select this particular option. So why have it as an option. This will help reduce clutter and too many things for users to think about.

**Comment by crstnn** [comment]
I think that if the users already have to understand the other parameters on the "BN Filter Parameters" page, another checkbox won't reduce the complexity much. Free text fields are more likely a cause for confusion (such as "Fixed Delta" and "Rolling Window"). I don't think we're being any more avuncular to an end-user giving them one less degree of freedom here. Up to you guys though.

**Comment by jamescmorley** [comment]
It is just that we want the experience to be like with the HP filter, which always returns a cycle of the same length as the levels series. The option has very little impact on estimates in the other periods. So we think it is simplest to always have the option on. The only reason not to would be to exactly (to many decimals) the result in the original paper with the original vintage of real GDP data. But that can be done with the Matlab or R code if someone needed to do it. Users of the website don't need to think about the option and should always have the iterated backcast results.

So let's drop making this an option for users, but always have it on in the background.

**Comment by crstnn** [comment]
That makes sense. This change will be effective in the next deployment.
