### ISSUE TITLE
Remove "Computed Percentages" Option

### ISSUE THREAD

**Issue by crstnn** [crstnn/BeveridgeNelsonFilter#2]
Instead replace with checkbox "Multiply by 100"

**Comment by crstnn** [comment]
Note:
option to specify if percentages are computed:
pcode == "np" [no change] -- Default --
pcode == "p1" [multiply by 100]
pcode == "p4" [multiply by 400, annualised quarterly rate]
pcode == "p12" [multiply by 1200, annualised monthly rate]

**Comment by jamescmorley** [comment]
Maybe can we make the checkbox "100 times natural logarithm" as this should always be what is selected for levels series like real GDP?

**Comment by jamescmorley** [comment]
So I think you don't need to change this anymore. The only thing is maybe remove "Ideal" in the two cases. E.g., "4th Difference (for Quarterly Data)". Sometimes it is ideal. Sometimes not.

**Comment by jamescmorley** [comment]
Sorry, I shouldn't have closed this yet given the suggested wording change to remove "Ideal".
