### ISSUE TITLE
Have Default Frequency as "Quarterly"

### ISSUE THREAD

**Issue by crstnn** [crstnn/BeveridgeNelsonFilter#3]

**Comment by jamescmorley** [comment]
And put "Undated" last. Also, how do we handle hourly or by the minute with the calendar?

**Comment by crstnn** [comment]
I'm still yet to figure that out. I'm considering perhaps a completely different 'picker' for some of the options.

**Comment by crstnn** [comment]
This will be fixed when we do the next server push as there are other updates that will cause errors if I am to deploy this now.

**Comment by crstnn** [comment]
This is fixed in the code but not deployed yet. I'll deploy the frontend update when we do the next server push as there are other updates that will cause errors if I am to deploy this now.
