### ISSUE TITLE
Graph Default without CI

### ISSUE THREAD

**Issue by crstnn** [crstnn/BeveridgeNelsonFilter#6]
Remove default confidence intervals

**Comment by jamescmorley** [comment]
Maybe make "95% confidence intervals" a box to tick on the BN Filter Parameters page (instead of "Iterative Backcasting", which should be moved to the previous page).

**Comment by crstnn** [comment]
I was planning to put the tickbox option on the graph page as the CI is already calculated anyway (so people should be able to toggle it on and off there). Let me know what you think.

**Comment by jamescmorley** [comment]
I think it is better to have people choose this before they see the graph. So I would put it on the BN Filter Parameters page. Again, my preference is that the default is unticked. Then if it is not ticked, the CSV should only have the cycle series, not the confidence bands.

**Comment by jamescmorley** [comment]
Looks good. But I think it should say "95% Confidence Intervals" instead of "Display Confidence Intervals".

**Comment by crstnn** [comment]
I'm thinking about moving the transformations to the next page as well. To free up some space for the FRED options.
